---
title: "Rough Draft"
output: pdf_notebook
---

```{r}
data <- read.csv('./data/pu_ssocs10.csv', sep='\t')
```

What are we trying to predict?

```{r}
cols <- c()
nas <- c()

for (col in colnames(data)) {
  perc_na <- sum(data[,col] %in% c(-1, NA)) / nrow(data)
  cols <- c(cols, col)
  nas <- c(nas, perc_na)
}

data_na <- data.frame(cols, nas)
colnames(data_na) <- c('col', 'perc_na')
data_na[order(-data_na$perc_na),]$col[43:194] # remove resampling, imputation, X, and all columns with NA
```

```{r}
# linear, poisson regression
# 
library(dplyr)
library(plyr)

newdata <- select(data,
                   #Predictors
                   C0568, C0452, C0436, DISRUPT,SVPOL10, C0560, 
                  #Response Variable
                   C0538,INCPOL10, GANGHATE, C0294)

newdata <- rename(newdata, c("C0568" = "Attendance","C0452" = "Loss_of_privlege", 
                  "C0436" =  "Loss_of_bus", "DISRUPT" = "Number_of_disruptions", 
                  "SVPOL10" = "Violent_incedents_to_police", "C0560" = "Crime_where_students_live",
                  "C0538" = "Classroom_changes", "INCPOL10" = "Incidents_reported_to_police",
                  "GANGHATE" = "Gang_related_activites", "C0294" = "Lack_of_funds"))
```


```{r}
#Plotting 

```



